# Le Quoc Hung 22712771


In [2]:
#k truyen index
import pandas as pd
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [5]:
#truyen index
s=pd.Series([1,2,3,4],index=(["a","b","c","d"]))
print(s)

a    1
b    2
c    3
d    4
dtype: int64


In [6]:
#tao series tu dict
data={'a':-1.3,'b':11.7,'d':2.0}
ser=pd.Series(data,index=['a','b','c','d'])
print(ser)

a    -1.3
b    11.7
c     NaN
d     2.0
dtype: float64


In [7]:
#gia tri lap lai de phu hop do dai
se=pd.Series(5,index=[1,2,3,4,5])
print(se)

1    5
2    5
3    5
4    5
5    5
dtype: int64


In [8]:
#tao du lieu 
import numpy as np
S=pd.Series(np.random.randint(100,size=4))
print(S)
print(S.values)
print(S.index)

0     2
1    42
2    70
3    32
dtype: int32
[ 2 42 70 32]
RangeIndex(start=0, stop=4, step=1)


In [10]:
chi_so=["ke toan",'KT','CNTT','Co khi']
gia_tri=[310,360,580,340]
S=pd.Series(gia_tri,index=chi_so)
print(S)
print(S.index)
print(S.values)

ke toan    310
KT         360
CNTT       580
Co khi     340
dtype: int64
Index(['ke toan', 'KT', 'CNTT', 'Co khi'], dtype='object')
[310 360 580 340]


In [11]:
#chi so trung nhau
chi_so=["KT",'KT','CNTT','Co khi']
gia_tri=[310,360,580,340]
S=pd.Series(gia_tri,index=chi_so)
print(S)
print(S.index)
print(S.values)

KT        310
KT        360
CNTT      580
Co khi    340
dtype: int64
Index(['KT', 'KT', 'CNTT', 'Co khi'], dtype='object')
[310 360 580 340]


In [12]:
#lay du lieu tai index cu the
data={'a':-1.3,'b':11.7,'d':2.0}
ser=pd.Series(data,index=['a','b','c','d'])
print(ser['a'])
print(ser['c'])

-1.3
nan


In [14]:
#lay du lieu tu dau den vi tri cu the
data={'a':-1.3,'b':11.7,'d':2.0}
ser=pd.Series(data,index=['a','b','c','d'])
print(ser[:'b'])


a    -1.3
b    11.7
dtype: float64


In [15]:
#lay 3 du lieu dau
data={'a':-1.3,'b':11.7,'d':2.0}
ser=pd.Series(data,index=['a','b','c','d'])
print(ser[:3])

a    -1.3
b    11.7
c     NaN
dtype: float64


In [21]:
#lay 2 du lieu cuoi
data={'a':-1.3,'b':11.7,'d':2.0}
ser=pd.Series(data,index=['a','b','c','d'])
print(ser[2:])

c    NaN
d    2.0
dtype: float64


In [22]:
#chuyen sang dang khac- lay dang array cua series bang numpy.array
data={'a':-1.3,'b':11.7,'d':2.0}
ser=pd.Series(data,index=['a','b','c','d'])
a=np.array(ser)
print(a)

[-1.3 11.7  nan  2. ]


In [23]:
#truy xuat du lieu thong qua chi so
chi_so=["KT",'KT','CNTT','Co khi']
gia_tri=[310,360,580,340]
S=pd.Series(gia_tri,index=chi_so)
print(S['Co khi'])
print(S['KT'])
print(S['CNTT'])

340
KT    310
KT    360
dtype: int64
580


In [26]:
#phep toan tren series
chi_so=["KT",'PM','CNTT','Co khi']
gia_tri=[310,360,580,340]
#chi so giong thi gop , neu khong thi nan
S=pd.Series(gia_tri,index=chi_so)
P=pd.Series([100,100],['CNTT','PM'])
Y=P+S
print(Y)


CNTT      680.0
Co khi      NaN
KT          NaN
PM        460.0
dtype: float64


In [27]:
#ham apply
def Tang(x):
    return x if x >500 else x+1000
chi_so=['Ke toan','KT','CNTT','Co khi']
gia_tri=[310,360,580,340]
s=pd.Series(gia_tri,chi_so)
#ap dung tang tren S (khong thay doi S)
print(s.apply(Tang))

Ke toan    1310
KT         1360
CNTT        580
Co khi     1340
dtype: int64


In [28]:
#tao data frame
#tao dict tu series
s={'mot': pd.Series([1,2,3,5],index=['a','b','c','e']),'hai': pd.Series([1,2,3,4],index=['a','b','c','d'])}
#tao data fr tu dict
df=pd.DataFrame(s)
print(df)

   mot  hai
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
e  5.0  NaN


In [29]:

#tao dict tu series
s={'mot': pd.Series([1,2,3,5],index=['a','b','c','e']),'hai': pd.Series([1,2,3,4],index=['a','b','c','d'])}
#tao data fr tu dict theo index duoc chon
df=pd.DataFrame(s,index=['a','c','d'])
print(df)

   mot  hai
a  1.0    1
c  3.0    3
d  NaN    4


In [30]:
#tao df tu list
names=['MIT','Stanford','DHTL']
df=pd.DataFrame(names)
print(df)
names_rank=[['MIT',1],['Stanford',2],['DHTL',3]]
df=pd.DataFrame(names_rank)
print(df)

          0
0       MIT
1  Stanford
2      DHTL
          0  1
0       MIT  1
1  Stanford  2
2      DHTL  3


In [31]:
#tao df tu dict  cac list
crimes_rates = {
"Year":[1960,1961,1962,1963,1964],"Population":[179323175,182992000,185771000,188483000,191141000],"Total":[3384200,3488000,3752200,4109500,4564600],
"Violent":[288460,289390,301510,316970,364220] }
crimes_dataframe = pd.DataFrame(crimes_rates)
print(crimes_dataframe)

   Year  Population    Total  Violent
0  1960   179323175  3384200   288460
1  1961   182992000  3488000   289390
2  1962   185771000  3752200   301510
3  1963   188483000  4109500   316970
4  1964   191141000  4564600   364220


In [32]:
#tao df tu list cac dict
data = [ {'MIT': 5000, 'Stanford': 4500, "DHTL":15000},
{'MIT': 1, 'Stanford': 2, "DHTL":200} ]
df = pd.DataFrame(data, index=['NumOfStudents', "ranking"])
print(df)
print(df.DHTL.dtype)

                MIT  Stanford   DHTL
NumOfStudents  5000      4500  15000
ranking           1         2    200
int64


In [33]:
#tao df tu dict series
data = { "one": pd.Series([1,23,45], index = [1,2,3]),
"two": pd.Series([1000,2400,1132,3434], index = [1,2,3,4]) }
df = pd.DataFrame(data)
print(df)

    one   two
1   1.0  1000
2  23.0  2400
3  45.0  1132
4   NaN  3434


In [34]:
s = {'một': pd.Series([1., 2., 3., 5.], index=['a', 'b', 'c', 'e']),'hai': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),
'ba': pd.Series([9., -1.3, 3.5, 41.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(s)
# chon cot hai
df_hai = df['hai']
print(df_hai)

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
Name: hai, dtype: float64


In [37]:
s = {'một': pd.Series([1., 2., 3., 5.], index=['a', 'b', 'c', 'e']),'hai': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),
'ba': pd.Series([9., -1.3, 3.5, 41.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(s)
# them cot bon theo cong thuc
df['bốn'] = df['hai'] - df['ba']
print(df)
# thêm cột với giá trị vô hướng (scalar value)
df['Chuẩn'] = 'OK'
# thêm cột không cùng số lượng index với DataFrame
df['Khác'] = df['hai'][:3]
# thêm cột True/False theo điều kiện
df['KT'] = df['một'] == 3.0
# dùng hàm insert. Cột "chèn" bên dưới sẽ ở vị trí 2 (tính từ 0), có giá trị bằng cột một
df.insert(2, 'chèn', df['một'])
print(df)

   một  hai    ba   bốn
a  1.0  1.0   9.0  -8.0
b  2.0  2.0  -1.3   3.3
c  3.0  3.0   3.5  -0.5
d  NaN  4.0  41.1 -37.1
e  5.0  NaN   NaN   NaN
   một  hai  chèn    ba   bốn Chuẩn  Khác     KT
a  1.0  1.0   1.0   9.0  -8.0    OK   1.0  False
b  2.0  2.0   2.0  -1.3   3.3    OK   2.0  False
c  3.0  3.0   3.0   3.5  -0.5    OK   3.0   True
d  NaN  4.0   NaN  41.1 -37.1    OK   NaN  False
e  5.0  NaN   5.0   NaN   NaN    OK   NaN  False


In [38]:
s = {'một': pd.Series([1., 2., 3., 5.], index=['a', 'b', 'c', 'e']),'hai': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),
'ba': pd.Series([9., -1.3, 3.5, 41.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(s)
# xóa cột hai
del df['hai']
# pop cột ba với dict tv_ba
tv_ba = df.pop('ba')
print(df)

   một
a  1.0
b  2.0
c  3.0
d  NaN
e  5.0


In [43]:
s = {'một': pd.Series([1., 2., 3., 5.], index=['a', 'b', 'c', 'e']),'hai': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),
'ba': pd.Series([9., -1.3, 3.5, 41.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(s)
# chọn dòng theo label
d = df.loc['e']
print(d)

một    5.0
hai    NaN
ba     NaN
Name: e, dtype: float64


In [42]:
s = {'một': pd.Series([1., 2., 3., 5.], index=['a', 'b', 'c', 'e']),'hai': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),
'ba': pd.Series([9., -1.3, 3.5, 41.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(s)
# chọn dòng theo vị trí nguyên
d = df.iloc[4]
print(d)

một    5.0
hai    NaN
ba     NaN
Name: e, dtype: float64


In [ ]:
s = {'một': pd.Series([1., 2., 3., 5.], index=['a', 'b', 'c', 'e']),'hai': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd']),
'ba': pd.Series([9., -1.3, 3.5, 41.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(s)
# cắt lấy ra từ dòng 3 đến dòng 4
d = df[2:4]
print(d)

   một  hai    ba
c  3.0  3.0   3.5
d  NaN  4.0  41.1


In [7]:
import numpy as np
df=pd.DataFrame(np.random.rand(23,4))
d=df[2:4]
print(d)

          0         1         2         3
2  0.693613  0.615805  0.232915  0.083934
3  0.667935  0.915380  0.966904  0.940386
